info:
  contact: {}
paths:
  /v1/captcha:
    get:
      description: 获取验证码
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 获取验证码
  /v1/ping:
    get:
      description: 健康检查接口
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查接口
  /v1/redirection/{code}:
    get:
      description: 链接重定向接口
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 链接重定向接口
swagger: "2.0"
