server:
  port: 9527
  address: 0.0.0.0
  mode: debug
  url404: https://volunteer.cdn-go.cn/404/latest/404.html
  urlfavicon: https://avatars.githubusercontent.com/u/65969632?v=4
  encrypted: true

database:
  dbType: mysql
  url: app_gt:app_gt@2022@tcp(mysql.microcloud.com:3388)/gt?charset=utf8&parseTime=True&loc=Local
  maxConn: 20
  maxOpen: 20
  InitData: false
#  InitSchema: true
  InitSchema: false

Cache:
  cacheType: l2
  # 默认缓存秒数
  defaultCacheTime: 1800

redis:
  addr: redis.microcloud.com:3307
  password: hewenping
  defaultDb: 3
  # 单位 秒
  timeout: 10
  poolSize: 20
  minConn: 1
  maxConn: 20

swagger:
  Host: localhost:9527
  version: 1.0
  basePath: /
  Schemes:
    - http(s)
  title: gt api doc
  description: gt api doc
  url: http://localhost:9527/swagger/doc.json

log:
  filename: ./log/gt.log
  level: debug
  # 单位 m
  maxSize: 10
  maxAge: 15
  maxBackups: 3

shortCode:
  # 段码长度
  length: 6
  # 每批次生成的短码个数,1<=size<=6
  size: 4

captcha:
  prefix: "gt:captcha:"
  # 单位 分钟
  validityPeriod: 3
  numberCodeLength: 6


encrypt:
  aesKey: ABCDEFGHIJKLMNO1

email:
  senderEmail: gotoadmin@163.com
  smtpServerHost: smtp.163.com
  auth: 
  Address: smtp.163.com:25
  enable: true

auth:
  anonymousUrls:
    # - /api/print
    - /favicon.ico
    - /v1/thread_callback
    - /v1/ping
    - /v1/redirection/:code
    - /oauth2/token
    - /swagger/*
    - /v1/captcha/*
    - /v1/shortCode
#    - /v1/test/*
    - /403.html

