info:
  contact: {}
paths:
  /v1/ping:
    get:
      description: 健康检查接口
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查接口
swagger: "2.0"
