server:
  port: 9527
  address: 0.0.0.0
  profiles:
    active: dev

database:
  type: mysql
  url: app_gt:app_gt@2022@tcp(localhost:3306)/gt?charset=utf8&parseTime=True&loc=Local
  maxConn: 20
  maxOpen: 20

redis:
  addr: 192.168.3.19:6379
  password: yihui@2021
  defaultDb: 3
  timeout: 3000
  poolSize: 20
  minConn: 1
  maxConn: 20

swagger:
  host: localhost:9527
  version: 1.0
  basePath: localhost:9527
  Schemes:
    -
  title: gt api doc
  description: gt api doc
  url: http://localhost:9527/swagger/doc.json
