definitions:
  result.Result:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: localhost:9527
info:
  contact:
    email: bingfenglai.dev@gmail.com
    name: Ferryman
    url: https://github.com/bingfenglai
  description: GT 后端接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://github.com/bingfenglai
  title: GT API
  version: "1.0"
paths:
  /v1/captcha/behavioral/images:
    get:
      description: 获取图片人机验证码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 获取图片人机验证码
      tags:
      - 验证码API
  /v1/captcha/behavioral/images/verity:
    post:
      description: 校验图片人机验证码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 校验图片人机验证码
      tags:
      - 验证码API
  /v1/captcha/email:
    get:
      description: 获取邮件验证码
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 获取邮件验证码
      tags:
      - 验证码API
  /v1/ping:
    get:
      description: 健康检查接口
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 健康检查接口
      tags:
      - 健康检查接口
  /v1/redirection:
    get:
      description: 链接重定向接口
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 链接重定向接口
      tags:
      - 短链接API
  /v1/shortCode:
    post:
      description: 生成短链接
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 生成短链接
      tags:
      - 短链接API
  /v1/tenant:
    post:
      description: 获取租户列表
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 获取租户列表
      tags:
      - 租户API
  /v1/user/info:
    post:
      consumes:
      - application/json
      description: 获取个人信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 获取个人信息
      tags:
      - 用户API
  /v1/user/password:
    put:
      consumes:
      - application/json
      description: 更改密码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 更改密码
      tags:
      - 用户API
swagger: "2.0"
